# torch.Tensor

В основе PyTorch лежит объект тензор — многомерный массив чисел, аналогичный numpy.ndarray, но с дополнительными возможностями.

Тензоры могут храниться на CPU или GPU и, при необходимости, отслеживать вычисленные градиенты.

Интерфейс PyTorch специально сделан похожим на NumPy, чтобы разработчику было удобно работать с данными.

Давайте посмотрим на несколько тензоров в действии.

In [1]:
import torch 


a = torch.tensor([1.0, 2.0, 3.0])              # 1D-тензор из списка
b = torch.zeros((2,3), dtype=torch.int64)      # матрица 2х3 из нулей(64-битные целы)
c = torch.rand(3, 3)                           # случайный тензор 3х3, равномерное распределение

print(a, a.dtype)
print(b, b.dtype)
print(c)

tensor([1., 2., 3.]) torch.float32
tensor([[0, 0, 0],
        [0, 0, 0]]) torch.int64
tensor([[0.7798, 0.4136, 0.0503],
        [0.2354, 0.7947, 0.9279],
        [0.0162, 0.9562, 0.2846]])


Тензоры поддерживают стандартные арифметические операции (сложение, умножение, матричные произведения и другие) и функциональные преобразования. Запустите код, чтобы проверить, как работают арифметические операции в PyTorch.

In [2]:
import torch


x = torch.tensor([1.0, -2.0, 3.0])
y = torch.exp(x)    # элемент-wise экспонента
z = x + y           # сложение поэлементно
print(z) 

tensor([ 3.7183, -1.8647, 23.0855])


При необходимости тензоры можно передавать на GPU:

In [3]:
if torch.cuda.is_available():
    a = a.to('cuda')  # переместить на CUDA-устройство 

Поскольку PyTorch тесно интегрирован с NumPy, тензоры можно конвертировать в numpy.ndarray и обратно — например, через torch.from_numpy или метод tensor.numpy().

# Автоматическое дифференцирование (Autograd)

PyTorch имеет встроенную систему автоматического дифференцирования (autograd), которая вычисляет градиенты. Если у тензора установлено свойство requires_grad=True, PyTorch запоминает все операции над ним и может потом вычислить градиенты по цепному правилу. Например:

In [4]:
x = torch.ones(2, 2, requires_grad=True)  # создаём тензор, указывая, что нужны градиенты
y = x * 2

z = y.mean()      # свёртка: усредняем все элементы
z.backward()      # выполняем обратный проход (backpropagation)
print(x.grad)     # смотрим градиент dz/dx

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])
